server:
  port: 8086

spring:
  application:
    name: admin-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://config-service:8888}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8762/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

