services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql-dock
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foundation
      MYSQL_USER: foundation
      MYSQL_PASSWORD: foundation123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Discovery Service (Eureka)
  discovery-service:
    build: ./discovery-service
    container_name: discovery-dock
    ports:
      - '8762:8762'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  # Config Service
  config-service:
    build: ./config-service
    container_name: config-dock
    ports:
      - '8888:8888'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8762/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - backend

  # Gateway Service
  gateway-service:
    build: ./gateway-service
    container_name: gateway-dock
    ports:
      - '9999:9999'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8762/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - backend

  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-dock
    ports:
      - '8081:8081'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8762/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/foundation?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=foundation
      - SPRING_DATASOURCE_PASSWORD=foundation123
    depends_on:
      config-service:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - backend

  # User Service
  user-service:
    build: ./user-service
    container_name: user-dock
    ports:
      - '8082:8082'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8762/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/foundation?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=foundation
      - SPRING_DATASOURCE_PASSWORD=foundation123
    depends_on:
      config-service:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - backend

  # Content Service (Temporarily disabled due to compilation errors)
  # content-service:
  #   build: ./content-service
  #   container_name: content-dock
  #   ports:
  #     - '8083:8083'
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8762/eureka/
  #     - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/foundation?useSSL=false&allowPublicKeyRetrieval=true
  #     - SPRING_DATASOURCE_USERNAME=foundation
  #     - SPRING_DATASOURCE_PASSWORD=foundation123
  #   depends_on:
  #     config-service:
  #       condition: service_healthy
  #     mysql:
  #       condition: service_healthy
  #   networks:
  #     - backend

  # Social Service
  social-service:
    build: ./social-service
    container_name: social-dock
    ports:
      - '8084:8084'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8762/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/foundation?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=foundation
      - SPRING_DATASOURCE_PASSWORD=foundation123
    depends_on:
      config-service:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - backend

  # Notification Service
  notification-service:
    build: ./notification-service
    container_name: notification-dock
    ports:
      - '8085:8085'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8762/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/foundation?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=foundation
      - SPRING_DATASOURCE_PASSWORD=foundation123
    depends_on:
      config-service:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - backend

  # Admin Service
  admin-service:
    build: ./admin-service
    container_name: admin-dock
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8762/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/foundation?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=foundation
      - SPRING_DATASOURCE_PASSWORD=foundation123
    depends_on:
      config-service:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - backend

  # Frontend Application
  frontend:
    build: ../frontend/fondation-sociale-frontend
    container_name: frontend-dock
    ports:
      - "4200:4200"
    depends_on:
      gateway-service:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
    driver: local
