server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://config-service:8888}
  datasource:
    url: jdbc:mysql://mysql:3306/foundation?useSSL=false&allowPublicKeyRetrieval=true
    username: foundation
    password: foundation123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8762/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
